# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-06 05:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('course_connect', '0002_auto_20170205_1357'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('announcement_text', models.TextField()),
                ('author', models.CharField(max_length=100)),
                ('publish_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
