# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-16 16:26
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('course_connect', '0003_announcement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_title', models.CharField(max_length=100)),
                ('question_statement', models.CharField(max_length=1000)),
                ('author', models.CharField(max_length=100)),
                ('semester', models.IntegerField(default=3)),
                ('testcases', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None)),
                ('solutions', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None)),
                ('publish_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
